### ISSUE TITLE
Transfer project to clj-commons ? 

### ISSUE THREAD

**Issue by ieugen** [clj-commons/metrics-clojure#146]
Hello @michaelklishin , 

Are you open to transferring this project to clj-commons ? 
- https://github.com/clj-commons/ 
-  https://clj-commons.org/ 

I've noticed the project could use some TLC and has not seen a lot of activity over the past few years. 
I believe metrics are important to the overall Clojure community and it would be great to have a maintained solution for this.

Thanks, 
Eugen

Related: 
- https://github.com/metrics-clojure/metrics-clojure/issues/145
- Slack discussion on #clj-commons channel  https://clojurians.slack.com/archives/CE1A21MPF/p1698913155868979 

cc @slipset

**Comment by ieugen** [comment]
ping @michaelklishin . 
Did you see the issue? Did you consider it?

**Comment by michaelklishin** [comment]
I am OK with transferring this project. I can't know if any of the original authors may have a different opinion.

**Comment by ieugen** [comment]
Thank you for getting back.

Do you keep in touch with the original authors to contact them? 
I can ping them if you let me know - but I imagine they might not reply to me that easily :) . 
It would be best to have them participate in this discussion.

If we move forward, this is the process for accepting new projects https://clj-commons.org/accepting-projects.html 
And this is the expected maintenance https://clj-commons.org/maintaining-projects.html . 
I am willing to work on the steps required to transfer the project.

**Comment by sjl** [comment]
I'm the original author, I have no opinions either way.

**Comment by seancorfield** [comment]
I believe one of the maintainers here with the admin rights to transfer the repo will need to be added to the `clj-commons` organization in order to initiate the transfer: should that be you @sjl ? Or @michaelklishin if you have sufficient rights here?

**Comment by michaelklishin** [comment]
@seancorfield @ieugen all done.
